spring.application.name=backblio
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:dbBlio;DB_CLOSE_DELAY=-1;
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=ahmed
spring.datasource.password=diallo
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
#app.secret-key=azertyubxgvdtggjjusegtlompbvjgffjfdgdhdgbcrr
#app.expiration-time=400000